<?php


namespace App\Domain\Enums;

// todo legacy

/**
 * Class LanguageEnum
 * @method static self FROM_LANG()
 */
class LanguageEnum extends Enum
{
    /**
     * __callStatic()
     */
    public const FROM_LANG = 'fromlang';

    private $origin;
    /**
     * Default frwiki lang
     *
     * @var string
     */
    private $frlang;

    // Data
    private $english_to_french
        = [
            "Abkhazian" => "abkhaze",
            "Achinese" => "aceh",
            "Acoli" => "acoli",
            "Adangme" => "adangmé",
            "Adyghe" => "adyghé",
            "Afar" => "afar",
            "Afrihili" => "afrihili",
            "Afrikaans" => "afrikaans",
            "Afro-Asiatic languages" => "langues afro-asiatiques",
            "Ainu (Japan)" => "aïnou",
            "Akan" => "akan",
            "Akkadian" => "akkadien",
            "Albanian" => "albanais",
            "Aleut" => "aléoute",
            "Algonquian languages" => "langues algonquiennes",
            "Altaic languages" => "langues altaïques",
            "Amharic" => "amharique",
            "Ancient Greek (to 1453)" => "grec ancien",
            "Angika" => "angika",
            "Apache languages" => "langues apaches",
            "Arabic" => "arabe",
            "Aragonese" => "aragonais",
            "Arapaho" => "arapaho",
            "Arawak" => "arawak",
            "Artificial languages" => "langues artificielles",
            "Assamese" => "assamais",
            "Asturian" => "asturien",
            "Athapascan languages" => "langues athapascanes",
            "Australian languages" => "langues australiennes",
            "Austronesian languages" => "langues austronésiennes",
            "Avaric" => "avar",
            "Avestan" => "avestique",
            "Awadhi" => "awadhi",
            "Aymara" => "aymará",
            "Azerbaijani" => "azéri",
            "Balinese" => "balinais",
            "Baltic languages" => "langues baltes",
            "Baluchi" => "baloutche",
            "Bambara" => "bambara",
            "Bamileke languages" => "langues bamilékées",
            "Bantu languages" => "langues bantoues",
            "Basa (Cameroon)" => "basa",
            "Bashkir" => "bachkir",
            "Batak languages" => "langues batak",
            "Beja" => "bedja",
            "Belarusian" => "biélorusse",
            "Bemba (Zambia)" => "bemba",
            "Bengali" => "bengalî",
            "Berber languages" => "langues berbères",
            "Bhojpuri" => "bhodjpouri",
            "Bihari languages" => "bihari",
            "Bikol" => "bikol",
            "Bilin" => "blin",
            "Bini" => "bini",
            "Bislama" => "bichelamar",
            "Blissymbols" => "symboles Bliss",
            "Bosnian" => "bosniaque",
            "Braj" => "braj",
            "Breton" => "breton",
            "Buginese" => "bugi",
            "Bulgarian" => "bulgare",
            "Buriat" => "bouriate",
            "Caddo" => "caddo",
            "Catalan" => "catalan",
            "Caucasian languages" => "langues caucasiennes",
            "Cebuano" => "cébouano",
            "Celtic languages" => "langues celtiques",
            "Central American Indian languages" => "langues indiennes d'Amérique centrale",
            "Central Khmer" => "khmer central",
            "Chagatai" => "djaghataï",
            "Chamic languages" => "langues chames",
            "Chamorro" => "chamorro",
            "Chechen" => "tchétchène",
            "Cherokee" => "cherokee",
            "Cheyenne" => "cheyenne",
            "Chibcha" => "chibcha",
            "Chinese" => "chinois",
            "Chinook jargon" => "chinook jargon",
            "Chipewyan" => "chipewyan",
            "Choctaw" => "choctaw",
            "Church Slavic" => "slavon d'église",
            "Chuukese" => "chuuk",
            "Chuvash" => "tchouvache",
            "Classical Newari" => "newari classique",
            "Classical Syriac" => "syriaque classique",
            "Coptic" => "copte",
            "Cornish" => "cornique",
            "Corsican" => "corse",
            "Cree" => "cree",
            "Creek" => "muskogee",
            "Creoles and pidgins" => "créoles",
            "Crimean Tatar" => "tatar de Crimée",
            "Croatian" => "croate",
            "Cushitic languages" => "langues couchitiques",
            "Czech" => "tchèque",
            "Dakota" => "dakota",
            "Danish" => "danois",
            "Dargwa" => "dargwa",
            "Delaware" => "delaware",
            "Dhivehi" => "maldivien",
            "Dinka" => "dinka",
            "Dogri (macrolanguage)" => "dogri",
            "Dogrib" => "dogrib",
            "Dravidian languages" => "langues dravidiennes",
            "Duala" => "douala",
            "Dutch" => "néerlandais",
            "Dyula" => "dioula",
            "Dzongkha" => "dzongkha",
            "Eastern Frisian" => "frison oriental",
            "Efik" => "éfik",
            "Egyptian (Ancient)" => "égyptien ancien",
            "Ekajuk" => "ekajuk",
            "Elamite" => "élamite",
            "English" => "anglais",
            "English based Creoles and pidgins" => "créoles et pidgins basés sur l'anglais",
            "Erzya" => "erza",
            "Esperanto" => "espéranto",
            "Estonian" => "estonien",
            "Ewe" => "éwé",
            "Ewondo" => "éwondo",
            "Fang (Equatorial Guinea)" => "fang",
            "Fanti" => "fanti",
            "Faroese" => "féroïen",
            "Fijian" => "fidjien",
            "Filipino" => "filipino",
            "Finnish" => "finnois",
            "Finno-Ugrian languages" => "langues finno-ougriennes",
            "Fon" => "fon",
            "French" => "français",
            "French-Based Creoles and pidgins" => "créoles et pidgins basés sur le français",
            "Friulian" => "frioulan",
            "Fulah" => "peul",
            "Ga" => "ga",
            "Galibi Carib" => "galibi",
            "Galician" => "galicien",
            "Ganda" => "ganda",
            "Gayo" => "gayo",
            "Gbaya (Central African Republic)" => "gbaya",
            "Geez" => "guèze",
            "German" => "allemand",
            "Germanic languages" => "langues germaniques",
            "Gilbertese" => "gilbertin",
            "Gondi" => "gondî",
            "Gorontalo" => "gorontalo",
            "Gothic" => "gotique",
            "Grebo" => "grébo",
            "Guarani" => "Guarani",
            "Gwichʼin" => "gwich'in",
            "Haida" => "haïda",
            "Haitian" => "haïtien",
            "Hausa" => "haoussa",
            "Hawaiian" => "hawaïen",
            "Hebrew" => "hébreu",
            "Herero" => "héréro",
            "Hiligaynon" => "hiligaïnon",
            "Himachali languages" => "himachali",
            "Hindi" => "hindi",
            "Hiri Motu" => "hiri motou",
            "Hittite" => "hittite",
            "Hmong" => "hmong",
            "Hungarian" => "hongrois",
            "Hupa" => "houpa",
            "Iban" => "iban",
            "Icelandic" => "islandais",
            "Ido" => "ido",
            "Igbo" => "igbo",
            "Ijo languages" => "langues ijo",
            "Iloko" => "ilocano",
            "Inari Sami" => "sâme d'Inari",
            "Indic languages" => "langues indo-aryennes",
            "Indo-European languages" => "langues indo-européennes",
            "Indonesian" => "indonésien",
            "Ingush" => "ingouche",
            "Interlingua (International Auxiliary Lan" => "interlingua",
            "Interlingue" => "interlingue",
            "Inuktitut" => "inuktitut",
            "Inupiaq" => "inupiaq",
            "Iranian languages" => "langues iraniennes",
            "Irish" => "irlandais",
            "Iroquoian languages" => "langues iroquoises",
            "Italian" => "italien",
            "Japanese" => "japonais",
            "Javanese" => "javanais",
            "Judeo-Arabic" => "judéo-arabe",
            "Judeo-Persian" => "judéo-persan",
            "Kabardian" => "kabarde",
            "Kabyle" => "kabyle",
            "Kachin" => "jinghpo",
            "Kalaallisut" => "groenlandais",
            "Kalmyk" => "kalmouk",
            "Kamba (Kenya)" => "kamba",
            "Kannada" => "kannada",
            "Kanuri" => "kanouri",
            "Kara-Kalpak" => "karakalpak",
            "Karachay-Balkar" => "karatchaï-balkar",
            "Karelian" => "carélien",
            "Karen languages" => "langues karens",
            "Kashmiri" => "kashmiri",
            "Kashubian" => "cachoube",
            "Kawi" => "kawi",
            "Kazakh" => "kazakh",
            "Khasi" => "khasi",
            "Khoisan languages" => "langues khoïsan",
            "Khotanese" => "khotanais",
            "Kikuyu" => "kikouyou",
            "Kinyarwanda" => "rwanda",
            "Kirghiz" => "kirghize",
            "Klingon" => "klingon",
            "Komi" => "kom",
            "Kongo" => "kongo",
            "Konkani (macrolanguage)" => "konkani",
            "Korean" => "coréen",
            "Kosraean" => "kosraéen",
            "Kpelle" => "kpellé",
            "Kru languages" => "langues krou",
            "Kuanyama" => "kuanyama",
            "Kumyk" => "koumyk",
            "Kurdish" => "kurde",
            "Kurukh" => "kouroukh",
            "Kutenai" => "koutenai",
            "Ladino" => "judéo-espagnol",
            "Lahnda" => "lahnda",
            "Lamba" => "lamba",
            "Land Dayak languages" => "langues Land Dayak",
            "Lao" => "lao",
            "Latin" => "latin",
            "Latvian" => "letton",
            "Lezghian" => "lezguien",
            "Limburgan" => "limbourgeois",
            "Lingala" => "lingala",
            "Lithuanian" => "lituanien",
            "Lojban" => "lojban",
            "Low German" => "bas-allemand",
            "Lower Sorbian" => "bas-sorabe",
            "Lozi" => "lozi",
            "Luba-Katanga" => "luba-Katanga",
            "Luba-Lulua" => "luba-Lulua",
            "Luiseno" => "luiseño",
            "Lule Sami" => "sâme de Lule",
            "Lunda" => "lounda",
            "Luo (Kenya and Tanzania)" => "luo",
            "Lushai" => "lousaï",
            "Luxembourgish" => "luxembourgeois",
            "Macedo-Romanian" => "aroumain",
            "Macedonian" => "macédonien",
            "Madurese" => "madurais",
            "Magahi" => "magahi",
            "Maithili" => "maïthili",
            "Makasar" => "makassar",
            "Malagasy" => "malgache",
            "Malayalam" => "malayalam",
            "Maltese" => "maltais",
            "Manchu" => "mandchou",
            "Mandar" => "mandar",
            "Mandingo" => "mandingue",
            "Manipuri" => "manipuri",
            "Manobo languages" => "langues manobo",
            "Manx" => "mannois",
            "Mapudungun" => "mapudungun",
            "Marathi" => "marathe",
            "Mari (Russia)" => "mari",
            "Marshallese" => "marshallais",
            "Marwari" => "marvari",
            "Masai" => "massaï",
            "Mayan languages" => "langues mayas",
            "Mende (Sierra Leone)" => "mendé",
            "Mi kmaq" => "mi'kmaq",
            "Middle Dutch (ca. 1050-1350)" => "Néerlandais, moyen",
            "Middle French (ca. 1400-1600)" => "moyen français",
            "Middle High German (ca. 1050-1500)" => "moyen haut-allemand",
            "Middle Irish (900-1200)" => "moyen irlandais",
            "Minangkabau" => "minangkabao",
            "Mirandese" => "mirandais",
            "Mohawk" => "mohawk",
            "Moksha" => "moksa",
            "Mon-Khmer languages" => "langues môn-khmer",
            "Mongo" => "mongo",
            "Mongolian" => "mongol",
            "Mossi" => "moré",
            "Munda languages" => "langues mounda",
            "N Ko" => "n'ko",
            "Nauru" => "nauri",
            "Navajo" => "navaho",
            "Ndonga" => "ndonga",
            "Neapolitan" => "napolitain",
            "Nepali" => "népalais",
            "Newari" => "nepal ghasa",
            "Nias" => "nias",
            "Niger-Kordofanian languages" => "langues nigéro-congolaises",
            "Nilo-Saharan languages" => "langues nilo-sahariennes",
            "Niuean" => "niué",
            "Nogai" => "nogaï",
            "North American Indian" => "langues indiennes d'Amérique du Nord",
            "North Ndebele" => "ndébélé du Nord",
            "Northern Frisian" => "frison septentrional",
            "Northern Sami" => "sâme du Nord",
            "Norwegian" => "Norvégien",
            "Norwegian Bokmål" => "norvégien bokmål",
            "Norwegian Nynorsk" => "norvégien nynorsk",
            "Nubian languages" => "langues nubiennes",
            "Nyamwezi" => "nyamwézi",
            "Nyanja" => "chichewa",
            "Nyankole" => "nyankolé",
            "Nyoro" => "nyoro",
            "Nzima" => "nzéma",
            "Occitan (post 1500)" => "occitan",
            "Official Aramaic (700-300 BCE)" => "araméen d'empire",
            "Ojibwa" => "ojibwa",
            "Old English (ca. 450-1100)" => "anglo-saxon",
            "Old French (842-ca. 1400)" => "ancien français",
            "Old High German (ca. 750-1050)" => "vieux haut allemand",
            "Old Irish (to 900)" => "irlandais ancien",
            "Old Norse" => "vieux norrois",
            "Old Persian (ca. 600-400 B.C.)" => "perse, vieux",
            "Old Provençal (to 1500)" => "provençal ancien",
            "Oriya" => "oriya",
            "Oromo" => "galla",
            "Osage" => "osage",
            "Ossetian" => "ossète",
            "Otomian languages" => "langues otomi",
            "Ottoman Turkish (1500-1928)" => "turc ottoman",
            "Pahlavi" => "pèhlevî",
            "Palauan" => "paluan",
            "Pali" => "pali",
            "Pampanga" => "pampangan",
            "Pangasinan" => "pangasinan",
            "Panjabi" => "pendjabi",
            "Papiamento" => "papiamento",
            "Papuan languages" => "langues papoues",
            "Pedi" => "sotho du Nord",
            "Philippine languages" => "langues philippines",
            "Phoenician" => "phénicien",
            "Pohnpeian" => "pohnpei",
            "Polish" => "polonais",
            "Portuguese" => "portugais",
            "Portuguese-Based Creoles and pidgins" => "créoles et pidgins basés sur le portugai",
            "Pushto" => "Pachto",
            "Quechua" => "quéchua",
            "Rajasthani" => "rajasthani",
            "Rapanui" => "rapanui",
            "Rarotongan" => "māori des îles Cook",
            "Romance languages" => "langues romanes",
            "Romanian" => "roumain",
            "Romansh" => "romanche",
            "Romany" => "romani",
            "Rundi" => "roundi",
            "Russian" => "russe",
            "Salishan languages" => "langues salish",
            "Samaritan Aramaic" => "samaritain",
            "Sami languages" => "langues sâmes",
            "Samoan" => "samoan",
            "Sandawe" => "sandawé",
            "Sango" => "sango",
            "Sanskrit" => "sanskrit",
            "Santali" => "santal",
            "Sardinian" => "sarde",
            "Sasak" => "sasak",
            "Scots" => "scots",
            "Scottish Gaelic" => "gaélique écossais",
            "Selkup" => "selkoupe",
            "Semitic languages" => "langues sémitiques",
            "Serbian" => "serbe",
            "Serer" => "sérère",
            "Shan" => "chan",
            "Shona" => "shona",
            "Sichuan Yi" => "yi de Sichuan",
            "Sicilian" => "sicilien",
            "Sidamo" => "sidamo",
            "Sign Languages" => "langue des signes",
            "Siksika" => "blackfoot",
            "Sindhi" => "sindhi",
            "Sinhala" => "singhalais",
            "Sino-Tibetan languages" => "langues sino-tibétaines",
            "Siouan languages" => "langues sioux",
            "Skolt Sami" => "sâme skolt",
            "Slave (Athapascan)" => "slavey (langue)",
            "Slavic languages" => "langues slaves",
            "Slovak" => "slovaque",
            "Slovenian" => "slovène",
            "Sogdian" => "sogdien",
            "Somali" => "somali",
            "Soninke" => "soninké",
            "South American Indian languages" => "langues indiennes d'Amérique du Sud",
            "South Ndebele" => "ndébélé du Sud",
            "Southern Altai" => "altaï du Sud",
            "Southern Sami" => "sâme du Sud",
            "Southern Sotho" => "sotho du Sud",
            "Spanish" => "espagnol",
            "Sranan Tongo" => "sranan tongo",
            "Sukuma" => "sukuma",
            "Sumerian" => "sumérien",
            "Sundanese" => "soundanais",
            "Susu" => "soussou",
            "Swahili (macrolanguage)" => "swahili",
            "Swati" => "swati",
            "Swedish" => "suédois",
            "Swiss German" => "alémanique",
            "Syriac" => "syriaque",
            "Tagalog" => "tagalog",
            "Tahitian" => "tahitien",
            "Tai languages" => "langues tai",
            "Tajik" => "tadjik",
            "Tamashek" => "tamacheq",
            "Tamil" => "tamoul",
            "Tatar" => "tatar",
            "Telugu" => "télougou",
            "Tereno" => "téréno",
            "Tetum" => "tetum",
            "Thai" => "thaï",
            "Tigre" => "tigré",
            "Tigrinya" => "tigrigna",
            "Timne" => "temne",
            "Tiv" => "tiv",
            "Tlingit" => "tlingit",
            "Tok Pisin" => "tok pisin",
            "Tokelau" => "tokelau",
            "Tonga (Nyasa)" => "tonga",
            "Tonga (Tonga Islands)" => "tongan",
            "Tsimshian" => "tsimchiane",
            "Tsonga" => "tsonga",
            "Tswana" => "tswana",
            "Tumbuka" => "tumbuka",
            "Tupi languages" => "langues tupi",
            "Turkish" => "turc",
            "Turkmen" => "turkmène",
            "Tuvalu" => "tuvalu",
            "Tuvinian" => "touva",
            "Twi" => "twi",
            "Udmurt" => "oudmourte",
            "Ugaritic" => "ougaritique",
            "Uighur" => "ouïgour",
            "Ukrainian" => "ukrainien",
            "Umbundu" => "umbundu",
            "Upper Sorbian" => "haut-sorabe",
            "Urdu" => "ourdou",
            "Uzbek" => "ouzbek",
            "Vai" => "vaï",
            "Venda" => "venda",
            "Vietnamese" => "vietnamien",
            "Volapük" => "volapük",
            "Votic" => "vote",
            "Wakashan languages" => "langues wakashennes",
            "Walloon" => "wallon",
            "Waray (Philippines)" => "waray",
            "Washo" => "washo",
            "Welsh" => "Gallois",
            "Western Frisian" => "frison occidental",
            "Wolaytta" => "wolaitta",
            "Wolof" => "wolof",
            "Xhosa" => "xhosa",
            "Yakut" => "iakoute",
            "Yao" => "yao",
            "Yapese" => "yapois",
            "Yiddish" => "yiddish",
            "Yoruba" => "langues yupik",
            "Zapotec" => "zapotèque",
            "Zenaga" => "zénaga",
            "Zhuang" => "zhuang",
            "Zulu" => "zoulou",
            "Zuni" => "zuñi",
        ];

    // TODO : virer parenthèses et voir pour comparaison sans "language(s)"
    private $iso2b_to_french
        = [
            "aar" => "afar",
            "aav" => "",
            "abk" => "abkhaze",
            "ace" => "aceh",
            "ach" => "acoli",
            "ada" => "adangmé",
            "ady" => "adyghé",
            "afa" => "langues afro-asiatiques",
            "afh" => "afrihili",
            "afr" => "afrikaans",
            "ain" => "aïnou",
            "aka" => "akan",
            "akk" => "akkadien",
            "alb" => "albanais",
            "ale" => "aléoute",
            "alg" => "langues algonquiennes",
            "alt" => "altaï du Sud",
            "alv" => "",
            "amh" => "amharique",
            "ang" => "anglo-saxon",
            "anp" => "angika",
            "apa" => "langues apaches",
            "aqa" => "",
            "aql" => "",
            "ara" => "arabe",
            "arc" => "araméen d'empire",
            "arg" => "aragonais",
            "arm" => "",
            "arn" => "mapudungun",
            "arp" => "arapaho",
            "art" => "langues artificielles",
            "arw" => "arawak",
            "asm" => "assamais",
            "ast" => "asturien",
            "ath" => "langues athapascanes",
            "auf" => "",
            "aus" => "langues australiennes",
            "ava" => "avar",
            "ave" => "avestique",
            "awa" => "awadhi",
            "awd" => "",
            "aym" => "aymará",
            "azc" => "",
            "aze" => "azéri",
            "bad" => "",
            "bai" => "langues bamilékées",
            "bak" => "bachkir",
            "bal" => "baloutche",
            "bam" => "bambara",
            "ban" => "balinais",
            "baq" => "",
            "bas" => "basa",
            "bat" => "langues baltes",
            "bej" => "bedja",
            "bel" => "biélorusse",
            "bem" => "bemba",
            "ben" => "bengalî",
            "ber" => "langues berbères",
            "bho" => "bhodjpouri",
            "bih" => "bihari",
            "bik" => "bikol",
            "bin" => "bini",
            "bis" => "bichelamar",
            "bla" => "blackfoot",
            "bnt" => "langues bantoues",
            "bos" => "bosniaque",
            "bra" => "braj",
            "bre" => "breton",
            "btk" => "langues batak",
            "bua" => "bouriate",
            "bug" => "bugi",
            "bul" => "bulgare",
            "bur" => "",
            "byn" => "blin",
            "cad" => "caddo",
            "cai" => "langues indiennes d'Amérique centrale",
            "car" => "galibi",
            "cat" => "catalan",
            "cau" => "langues caucasiennes",
            "cba" => "",
            "ccn" => "",
            "ccs" => "",
            "cdc" => "",
            "cdd" => "",
            "ceb" => "cébouano",
            "cel" => "langues celtiques",
            "cha" => "chamorro",
            "chb" => "chibcha",
            "che" => "tchétchène",
            "chg" => "djaghataï",
            "chi" => "chinois",
            "chk" => "chuuk",
            "chm" => "mari",
            "chn" => "chinook jargon",
            "cho" => "choctaw",
            "chp" => "chipewyan",
            "chr" => "cherokee",
            "chu" => "slavon d'église",
            "chv" => "tchouvache",
            "chy" => "cheyenne",
            "cmc" => "langues chames",
            "cop" => "copte",
            "cor" => "cornique",
            "cos" => "corse",
            "cpe" => "créoles et pidgins basés sur l'anglais",
            "cpf" => "créoles et pidgins basés sur le français",
            "cpp" => "créoles et pidgins basés sur le portugai",
            "cre" => "cree",
            "crh" => "tatar de Crimée",
            "crp" => "créoles",
            "csb" => "cachoube",
            "csu" => "",
            "cus" => "langues couchitiques",
            "cze" => "tchèque",
            "dak" => "dakota",
            "dan" => "danois",
            "dar" => "dargwa",
            "day" => "langues Land Dayak",
            "del" => "delaware",
            "den" => "slavey (langue)",
            "dgr" => "dogrib",
            "din" => "dinka",
            "div" => "maldivien",
            "dmn" => "",
            "doi" => "dogri",
            "dra" => "langues dravidiennes",
            "dsb" => "bas-sorabe",
            "dua" => "douala",
            "dum" => "Néerlandais, moyen",
            "dut" => "néerlandais",
            "dyu" => "dioula",
            "dzo" => "dzongkha",
            "efi" => "éfik",
            "egx" => "",
            "egy" => "égyptien ancien",
            "eka" => "ekajuk",
            "elx" => "élamite",
            "eng" => "anglais",
            "enm" => "",
            "epo" => "espéranto",
            "est" => "estonien",
            "esx" => "",
            "euq" => "",
            "ewe" => "éwé",
            "ewo" => "éwondo",
            "fan" => "fang",
            "fao" => "féroïen",
            "fat" => "fanti",
            "fij" => "fidjien",
            "fil" => "filipino",
            "fin" => "finnois",
            "fiu" => "langues finno-ougriennes",
            "fon" => "fon",
            "fox" => "",
            "fre" => "français",
            "frm" => "moyen français",
            "fro" => "ancien français",
            "frr" => "frison septentrional",
            "frs" => "frison oriental",
            "fry" => "frison occidental",
            "ful" => "peul",
            "fur" => "frioulan",
            "gaa" => "ga",
            "gay" => "gayo",
            "gba" => "gbaya",
            "gem" => "langues germaniques",
            "geo" => "",
            "ger" => "allemand",
            "gez" => "guèze",
            "gil" => "gilbertin",
            "gla" => "gaélique écossais",
            "gle" => "irlandais",
            "glg" => "galicien",
            "glv" => "mannois",
            "gme" => "",
            "gmh" => "moyen haut-allemand",
            "gmq" => "",
            "gmw" => "",
            "goh" => "vieux haut allemand",
            "gon" => "gondî",
            "gor" => "gorontalo",
            "got" => "gotique",
            "grb" => "grébo",
            "grc" => "grec ancien",
            "gre" => "",
            "grk" => "",
            "grn" => "Guarani",
            "gsw" => "alémanique",
            "gwi" => "gwich'in",
            "hai" => "haïda",
            "hat" => "haïtien",
            "hau" => "haoussa",
            "haw" => "hawaïen",
            "heb" => "hébreu",
            "her" => "héréro",
            "hil" => "hiligaïnon",
            "him" => "himachali",
            "hin" => "hindi",
            "hit" => "hittite",
            "hmn" => "hmong",
            "hmo" => "hiri motou",
            "hmx" => "",
            "hok" => "",
            "hrv" => "croate",
            "hsb" => "haut-sorabe",
            "hun" => "hongrois",
            "hup" => "houpa",
            "hyx" => "",
            "iba" => "iban",
            "ibo" => "igbo",
            "ice" => "islandais",
            "ido" => "ido",
            "iii" => "yi de Sichuan",
            "iir" => "",
            "ijo" => "langues ijo",
            "iku" => "inuktitut",
            "ile" => "interlingue",
            "ilo" => "ilocano",
            "ina" => "interlingua",
            "inc" => "langues indo-aryennes",
            "ind" => "indonésien",
            "ine" => "langues indo-européennes",
            "inh" => "ingouche",
            "ipk" => "inupiaq",
            "ira" => "langues iraniennes",
            "iro" => "langues iroquoises",
            "ita" => "italien",
            "itc" => "",
            "jav" => "javanais",
            "jbo" => "lojban",
            "jpn" => "japonais",
            "jpr" => "judéo-persan",
            "jpx" => "",
            "jrb" => "judéo-arabe",
            "kaa" => "karakalpak",
            "kab" => "kabyle",
            "kac" => "jinghpo",
            "kal" => "groenlandais",
            "kam" => "kamba",
            "kan" => "kannada",
            "kar" => "langues karens",
            "kas" => "kashmiri",
            "kau" => "kanouri",
            "kaw" => "kawi",
            "kaz" => "kazakh",
            "kbd" => "kabarde",
            "kdo" => "",
            "kha" => "khasi",
            "khi" => "langues khoïsan",
            "khm" => "khmer central",
            "kho" => "khotanais",
            "kik" => "kikouyou",
            "kin" => "rwanda",
            "kir" => "kirghize",
            "kmb" => "",
            "kok" => "konkani",
            "kom" => "kom",
            "kon" => "kongo",
            "kor" => "coréen",
            "kos" => "kosraéen",
            "kpe" => "kpellé",
            "krc" => "karatchaï-balkar",
            "krl" => "carélien",
            "kro" => "langues krou",
            "kru" => "kouroukh",
            "kua" => "kuanyama",
            "kum" => "koumyk",
            "kur" => "kurde",
            "kut" => "koutenai",
            "lad" => "judéo-espagnol",
            "lah" => "lahnda",
            "lam" => "lamba",
            "lao" => "lao",
            "lat" => "latin",
            "lav" => "letton",
            "lez" => "lezguien",
            "lim" => "limbourgeois",
            "lin" => "lingala",
            "lit" => "lituanien",
            "lol" => "mongo",
            "loz" => "lozi",
            "ltz" => "luxembourgeois",
            "lua" => "luba-Lulua",
            "lub" => "luba-Katanga",
            "lug" => "ganda",
            "lui" => "luiseño",
            "lun" => "lounda",
            "luo" => "luo",
            "lus" => "lousaï",
            "mac" => "macédonien",
            "mad" => "madurais",
            "mag" => "magahi",
            "mah" => "marshallais",
            "mai" => "maïthili",
            "mak" => "makassar",
            "mal" => "malayalam",
            "man" => "mandingue",
            "mao" => "",
            "map" => "langues austronésiennes",
            "mar" => "marathe",
            "mas" => "massaï",
            "may" => "",
            "mdf" => "moksa",
            "mdr" => "mandar",
            "men" => "mendé",
            "mga" => "moyen irlandais",
            "mic" => "mi'kmaq",
            "min" => "minangkabao",
            "mis" => "",
            "mkh" => "langues môn-khmer",
            "mlg" => "malgache",
            "mlt" => "maltais",
            "mnc" => "mandchou",
            "mni" => "manipuri",
            "mno" => "langues manobo",
            "moh" => "mohawk",
            "mon" => "mongol",
            "mos" => "moré",
            "mul" => "",
            "mun" => "langues mounda",
            "mus" => "muskogee",
            "mwl" => "mirandais",
            "mwr" => "marvari",
            "myn" => "langues mayas",
            "myv" => "erza",
            "nah" => "",
            "nai" => "langues indiennes d'Amérique du Nord",
            "nap" => "napolitain",
            "nau" => "nauri",
            "nav" => "navaho",
            "nbl" => "ndébélé du Sud",
            "nde" => "ndébélé du Nord",
            "ndo" => "ndonga",
            "nds" => "bas-allemand",
            "nep" => "népalais",
            "new" => "nepal ghasa",
            "ngf" => "",
            "nia" => "nias",
            "nic" => "langues nigéro-congolaises",
            "niu" => "niué",
            "nno" => "norvégien nynorsk",
            "nob" => "norvégien bokmål",
            "nog" => "nogaï",
            "non" => "vieux norrois",
            "nor" => "Norvégien",
            "nqo" => "n'ko",
            "nso" => "sotho du Nord",
            "nub" => "langues nubiennes",
            "nwc" => "newari classique",
            "nya" => "chichewa",
            "nym" => "nyamwézi",
            "nyn" => "nyankolé",
            "nyo" => "nyoro",
            "nzi" => "nzéma",
            "oci" => "occitan",
            "oji" => "ojibwa",
            "omq" => "",
            "omv" => "",
            "ori" => "oriya",
            "orm" => "galla",
            "osa" => "osage",
            "oss" => "ossète",
            "ota" => "turc ottoman",
            "oto" => "langues otomi",
            "paa" => "langues papoues",
            "pag" => "pangasinan",
            "pal" => "pèhlevî",
            "pam" => "pampangan",
            "pan" => "pendjabi",
            "pap" => "papiamento",
            "pau" => "paluan",
            "peo" => "perse, vieux",
            "per" => "",
            "phi" => "langues philippines",
            "phn" => "phénicien",
            "plf" => "",
            "pli" => "pali",
            "pol" => "polonais",
            "pon" => "pohnpei",
            "por" => "portugais",
            "poz" => "",
            "pqe" => "",
            "pqw" => "",
            "pra" => "",
            "pro" => "provençal ancien",
            "pus" => "Pachto",
            "que" => "quéchua",
            "qwe" => "",
            "raj" => "rajasthani",
            "rap" => "rapanui",
            "rar" => "māori des îles Cook",
            "roa" => "langues romanes",
            "roh" => "romanche",
            "rom" => "romani",
            "rum" => "roumain",
            "run" => "roundi",
            "rup" => "aroumain",
            "rus" => "russe",
            "sad" => "sandawé",
            "sag" => "sango",
            "sah" => "iakoute",
            "sai" => "langues indiennes d'Amérique du Sud",
            "sal" => "langues salish",
            "sam" => "samaritain",
            "san" => "sanskrit",
            "sas" => "sasak",
            "sat" => "santal",
            "scn" => "sicilien",
            "sco" => "scots",
            "sdv" => "",
            "sel" => "selkoupe",
            "sem" => "langues sémitiques",
            "sga" => "irlandais ancien",
            "sgn" => "langue des signes",
            "shn" => "chan",
            "sid" => "sidamo",
            "sin" => "singhalais",
            "sio" => "langues sioux",
            "sit" => "langues sino-tibétaines",
            "sla" => "langues slaves",
            "slo" => "slovaque",
            "slv" => "slovène",
            "sma" => "sâme du Sud",
            "sme" => "sâme du Nord",
            "smi" => "langues sâmes",
            "smj" => "sâme de Lule",
            "smn" => "sâme d'Inari",
            "smo" => "samoan",
            "sms" => "sâme skolt",
            "sna" => "shona",
            "snd" => "sindhi",
            "snk" => "soninké",
            "sog" => "sogdien",
            "som" => "somali",
            "son" => "",
            "sot" => "sotho du Sud",
            "spa" => "espagnol",
            "sqj" => "",
            "srd" => "sarde",
            "srn" => "sranan tongo",
            "srp" => "serbe",
            "srr" => "sérère",
            "ssa" => "langues nilo-sahariennes",
            "ssw" => "swati",
            "suk" => "sukuma",
            "sun" => "soundanais",
            "sus" => "soussou",
            "sux" => "sumérien",
            "swa" => "swahili",
            "swe" => "suédois",
            "syc" => "syriaque classique",
            "syd" => "",
            "syr" => "syriaque",
            "tah" => "tahitien",
            "tai" => "langues tai",
            "tam" => "tamoul",
            "tat" => "tatar",
            "tbq" => "",
            "tel" => "télougou",
            "tem" => "temne",
            "ter" => "téréno",
            "tet" => "tetum",
            "tgk" => "tadjik",
            "tgl" => "tagalog",
            "tha" => "thaï",
            "tib" => "",
            "tig" => "tigré",
            "tir" => "tigrigna",
            "tiv" => "tiv",
            "tkl" => "tokelau",
            "tlh" => "klingon",
            "tli" => "tlingit",
            "tmh" => "tamacheq",
            "tog" => "tonga",
            "ton" => "tongan",
            "tpi" => "tok pisin",
            "trk" => "",
            "tsi" => "tsimchiane",
            "tsn" => "tswana",
            "tso" => "tsonga",
            "tuk" => "turkmène",
            "tum" => "tumbuka",
            "tup" => "langues tupi",
            "tur" => "turc",
            "tut" => "langues altaïques",
            "tuw" => "",
            "tvl" => "tuvalu",
            "twi" => "twi",
            "tyv" => "touva",
            "udm" => "oudmourte",
            "uga" => "ougaritique",
            "uig" => "ouïgour",
            "ukr" => "ukrainien",
            "umb" => "umbundu",
            "und" => "",
            "urd" => "ourdou",
            "urj" => "",
            "uzb" => "ouzbek",
            "vai" => "vaï",
            "ven" => "venda",
            "vie" => "vietnamien",
            "vol" => "volapük",
            "vot" => "vote",
            "wak" => "langues wakashennes",
            "wal" => "wolaitta",
            "war" => "waray",
            "was" => "washo",
            "wel" => "Gallois",
            "wen" => "",
            "wln" => "wallon",
            "wol" => "wolof",
            "xal" => "kalmouk",
            "xgn" => "",
            "xho" => "xhosa",
            "xnd" => "",
            "yao" => "yao",
            "yap" => "yapois",
            "yid" => "yiddish",
            "yor" => "langues yupik",
            "ypk" => "",
            "zap" => "zapotèque",
            "zbl" => "symboles Bliss",
            "zen" => "zénaga",
            "zha" => "zhuang",
            "zhx" => "",
            "zle" => "",
            "zls" => "",
            "zlw" => "",
            "znd" => "",
            "zul" => "zoulou",
            "zun" => "zuñi",
        ];

    // Worlcat (eng) ISO2b => nom français de la langue (anglais)
    private $iso2b_to_frlang
        = [
            "aar" => "aa",
            "abk" => "ab",
            "ace" => "ace",
            "afr" => "af",
            "alb" => "sq",
            "amh" => "an",
            "ang" => "ang",
            "ara" => "ar",
            "asm" => "as",
            "ast" => "ast",
            "ave" => "ae",
            "aym" => "ay",
            "aze" => "az",
            "bak" => "ba",
            "bam" => "bm",
            "bel" => "be-tarask",
            "ben" => "bn",
            "bih" => "bh",
            "bik" => "bcl",
            "bis" => "bi",
            "bre" => "br",
            "bul" => "bg",
            "cat" => "ca",
            "cha" => "ch",
            "che" => "ce",
            "chi" => "zh",
            "chv" => "cv",
            "cor" => "kw",
            "cos" => "co",
            "crh" => "crh",
            "cze" => "cs",
            "dan" => "da",
            "dut" => "nl-be",
            "dzo" => "dz",
            "eng" => "en",
            "epo" => "eo",
            "est" => "et",
            "ewe" => "ee",
            "fij" => "fj",
            "fin" => "fi",
            "fre" => "fr",
            "fry" => "fy",
            "ful" => "ff",
            "fur" => "fur",
            "ger" => "de",
            "gez" => "gez",
            "gil" => "gil",
            "gle" => "ga",
            "glg" => "gl",
            "glv" => "gv",
            "grc" => "grc",
            "grn" => "gn",
            "hat" => "ht",
            "hau" => "ha",
            "heb" => "he",
            "hin" => "hif",
            "hrv" => "hr",
            "hsb" => "hsb",
            "hun" => "hu",
            "ibo" => "ig",
            "ice" => "is",
            "ido" => "io",
            "iku" => "iu",
            "ile" => "ie",
            "ina" => "ia",
            "ind" => "id",
            "ipk" => "ik",
            "ita" => "it",
            "jav" => "jv",
            "jpn" => "ja",
            "kaa" => "kaa",
            "kab" => "kab",
            "kal" => "kl",
            "kas" => "ks",
            "kaz" => "kk",
            "kir" => "ky",
            "kon" => "kg",
            "kor" => "ko",
            "kur" => "ku",
            "lad" => "lad",
            "lao" => "lo",
            "lat" => "la",
            "lav" => "lv",
            "lim" => "li",
            "lin" => "ln",
            "lit" => "lt",
            "ltz" => "lb",
            "lua" => "lua",
            "mac" => "mk-Latn",
            "mal" => "ml",
            "mlg" => "mg",
            "mlt" => "mt",
            "mon" => "mn",
            "mus" => "mus",
            "mwl" => "mwl",
            "nap" => "nap",
            "nbl" => "nr",
            "nde" => "nd",
            "nds" => "nds",
            "nep" => "ne",
            "new" => "new",
            "non" => "vn",
            "nor" => "no",
            "oci" => "oc",
            "ori" => "or",
            "oss" => "os",
            "pam" => "pam",
            "pan" => "pa",
            "pli" => "pi",
            "pol" => "pl",
            "por" => "pt",
            "pus" => "ps",
            "que" => "qu",
            "roh" => "roh",
            "rom" => "rmy",
            "rum" => "ro",
            "rup" => "roa-rup",
            "rus" => "ru-Latn",
            "sag" => "sg",
            "san" => "sa",
            "scn" => "scn",
            "sco" => "sco",
            "slo" => "sk",
            "slv" => "sl",
            "sma" => "se",
            "smo" => "sm",
            "sna" => "sn",
            "snd" => "sd",
            "som" => "so",
            "sot" => "sot",
            "spa" => "es",
            "srd" => "sc",
            "srp" => "sr",
            "sun" => "su",
            "swa" => "sw",
            "swe" => "sv",
            "tah" => "ty",
            "tam" => "ta",
            "tat" => "tt",
            "tel" => "te",
            "tgk" => "tg",
            "tgl" => "tl",
            "tha" => "th",
            "tsn" => "tn",
            "tso" => "ts",
            "tuk" => "tk",
            "tur" => "tu",
            "twi" => "tw",
            "ukr" => "uk",
            "urd" => "ur",
            "uzb" => "uz",
            "vie" => "vi",
            "vol" => "vo",
            "wel" => "cy",
            "wln" => "wa",
            "wol" => "wo",
            "xho" => "xh",
            "yid" => "yi",
            "zha" => "za",
            "zul" => "zu",
        ];

    // Worlcat (eng) ISO2b => code fr-wikipédia ( {{en}} )
    private $frlang_to_french
        = [
            "aa" => "afar",
            "ab" => "abkhaze",
            "ace" => "aceh",
            "af" => "afrikaans",
            "sq" => "albanais",
            "an" => "amharique",
            "ang" => "anglo-saxon",
            "ar" => "arabe",
            "as" => "assamais",
            "ast" => "asturien",
            "ae" => "avestique",
            "ay" => "aymará",
            "az" => "azéri",
            "ba" => "bachkir",
            "bm" => "bambara",
            "be-tarask" => "biélorusse",
            "bn" => "bengalî",
            "bh" => "bihari",
            "bcl" => "bikol",
            "bi" => "bichelamar",
            "br" => "breton",
            "bg" => "bulgare",
            "ca" => "catalan",
            "ch" => "chamorro",
            "ce" => "tchétchène",
            "zh" => "chinois",
            "cv" => "tchouvache",
            "kw" => "cornique",
            "co" => "corse",
            "crh" => "tatar de Crimée",
            "cs" => "tchèque",
            "da" => "danois",
            "nl-be" => "néerlandais",
            "dz" => "dzongkha",
            "en" => "anglais",
            "eo" => "espéranto",
            "et" => "estonien",
            "ee" => "éwé",
            "fj" => "fidjien",
            "fi" => "finnois",
            "fr" => "français",
            "fy" => "frison occidental",
            "ff" => "peul",
            "fur" => "frioulan",
            "de" => "allemand",
            "gez" => "guèze",
            "gil" => "gilbertin",
            "ga" => "irlandais",
            "gl" => "galicien",
            "gv" => "mannois",
            "grc" => "grec ancien",
            "gn" => "Guarani",
            "ht" => "haïtien",
            "ha" => "haoussa",
            "he" => "hébreu",
            "hif" => "hindi",
            "hr" => "croate",
            "hsb" => "haut-sorabe",
            "hu" => "hongrois",
            "ig" => "igbo",
            "is" => "islandais",
            "io" => "ido",
            "iu" => "inuktitut",
            "ie" => "interlingue",
            "ia" => "interlingua",
            "id" => "indonésien",
            "ik" => "inupiaq",
            "it" => "italien",
            "jv" => "javanais",
            "ja" => "japonais",
            "kaa" => "karakalpak",
            "kab" => "kabyle",
            "kl" => "groenlandais",
            "ks" => "kashmiri",
            "kk" => "kazakh",
            "ky" => "kirghize",
            "kg" => "kongo",
            "ko" => "coréen",
            "ku" => "kurde",
            "lad" => "judéo-espagnol",
            "lo" => "lao",
            "la" => "latin",
            "lv" => "letton",
            "li" => "limbourgeois",
            "ln" => "lingala",
            "lt" => "lituanien",
            "lb" => "luxembourgeois",
            "lua" => "luba-Lulua",
            "mk-Latn" => "macédonien",
            "ml" => "malayalam",
            "mg" => "malgache",
            "mt" => "maltais",
            "mn" => "mongol",
            "mus" => "muskogee",
            "mwl" => "mirandais",
            "nap" => "napolitain",
            "nr" => "ndébélé du Sud",
            "nd" => "ndébélé du Nord",
            "nds" => "bas-allemand",
            "ne" => "népalais",
            "new" => "nepal ghasa",
            "vn" => "vieux norrois",
            "no" => "Norvégien",
            "oc" => "occitan",
            "or" => "oriya",
            "os" => "ossète",
            "pam" => "pampangan",
            "pa" => "pendjabi",
            "pi" => "pali",
            "pl" => "polonais",
            "pt" => "portugais",
            "ps" => "Pachto",
            "qu" => "quéchua",
            "roh" => "romanche",
            "rmy" => "romani",
            "ro" => "roumain",
            "roa-rup" => "aroumain",
            "ru-Latn" => "russe",
            "sg" => "sango",
            "sa" => "sanskrit",
            "scn" => "sicilien",
            "sco" => "scots",
            "sk" => "slovaque",
            "sl" => "slovène",
            "se" => "sâme du Sud",
            "sm" => "samoan",
            "sn" => "shona",
            "sd" => "sindhi",
            "so" => "somali",
            "sot" => "sotho du Sud",
            "es" => "espagnol",
            "sc" => "sarde",
            "sr" => "serbe",
            "su" => "soundanais",
            "sw" => "swahili",
            "sv" => "suédois",
            "ty" => "tahitien",
            "ta" => "tamoul",
            "tt" => "tatar",
            "te" => "télougou",
            "tg" => "tadjik",
            "tl" => "tagalog",
            "th" => "thaï",
            "tn" => "tswana",
            "ts" => "tsonga",
            "tk" => "turkmène",
            "tu" => "turc",
            "tw" => "twi",
            "uk" => "ukrainien",
            "ur" => "ourdou",
            "uz" => "ouzbek",
            "vi" => "vietnamien",
            "vo" => "volapük",
            "cy" => "Gallois",
            "wa" => "wallon",
            "wo" => "wolof",
            "xh" => "xhosa",
            "yi" => "yiddish",
            "za" => "zhuang",
            "zu" => "zoulou",
        ];

    // FR-WIKIPEDIA ({{en}}) => français
    private $french_to_frlang
        = [
            "abkhaze" => "ab",
            "aceh" => "ace",
            "afar" => "aa",
            "afrikaans" => "af",
            "albanais" => "sq",
            "allemand" => "de",
            "amharique" => "an",
            "anglais" => "en",
            "anglo-saxon" => "ang",
            "arabe" => "ar",
            "aroumain" => "roa-rup",
            "assamais" => "as",
            "asturien" => "ast",
            "avestique" => "ae",
            "aymará" => "ay",
            "azéri" => "az",
            "bachkir" => "ba",
            "bambara" => "bm",
            "bas-allemand" => "nds",
            "bengalî" => "bn",
            "bichelamar" => "bi",
            "biélorusse" => "be-tarask",
            "bihari" => "bh",
            "bikol" => "bcl",
            "breton" => "br",
            "bulgare" => "bg",
            "catalan" => "ca",
            "chamorro" => "ch",
            "chinois" => "zh",
            "coréen" => "ko",
            "cornique" => "kw",
            "corse" => "co",
            "croate" => "hr",
            "danois" => "da",
            "dzongkha" => "dz",
            "espagnol" => "es",
            "espéranto" => "eo",
            "estonien" => "et",
            "éwé" => "ee",
            "fidjien" => "fj",
            "finnois" => "fi",
            "français" => "fr",
            "frioulan" => "fur",
            "frison occidental" => "fy",
            "galicien" => "gl",
            "Gallois" => "cy",
            "gilbertin" => "gil",
            "grec ancien" => "grc",
            "groenlandais" => "kl",
            "Guarani" => "gn",
            "guèze" => "gez",
            "haïtien" => "ht",
            "haoussa" => "ha",
            "haut-sorabe" => "hsb",
            "hébreu" => "he",
            "hindi" => "hif",
            "hongrois" => "hu",
            "ido" => "io",
            "igbo" => "ig",
            "indonésien" => "id",
            "interlingua" => "ia",
            "interlingue" => "ie",
            "inuktitut" => "iu",
            "inupiaq" => "ik",
            "irlandais" => "ga",
            "islandais" => "is",
            "italien" => "it",
            "japonais" => "ja",
            "javanais" => "jv",
            "judéo-espagnol" => "lad",
            "kabyle" => "kab",
            "karakalpak" => "kaa",
            "kashmiri" => "ks",
            "kazakh" => "kk",
            "kirghize" => "ky",
            "kongo" => "kg",
            "kurde" => "ku",
            "lao" => "lo",
            "latin" => "la",
            "letton" => "lv",
            "limbourgeois" => "li",
            "lingala" => "ln",
            "lituanien" => "lt",
            "luba-Lulua" => "lua",
            "luxembourgeois" => "lb",
            "macédonien" => "mk-Latn",
            "malayalam" => "ml",
            "malgache" => "mg",
            "maltais" => "mt",
            "mannois" => "gv",
            "mirandais" => "mwl",
            "mongol" => "mn",
            "muskogee" => "mus",
            "napolitain" => "nap",
            "ndébélé du Nord" => "nd",
            "ndébélé du Sud" => "nr",
            "néerlandais" => "nl-be",
            "nepal ghasa" => "new",
            "népalais" => "ne",
            "Norvégien" => "no",
            "occitan" => "oc",
            "oriya" => "or",
            "ossète" => "os",
            "ourdou" => "ur",
            "ouzbek" => "uz",
            "Pachto" => "ps",
            "pali" => "pi",
            "pampangan" => "pam",
            "pendjabi" => "pa",
            "peul" => "ff",
            "polonais" => "pl",
            "portugais" => "pt",
            "quéchua" => "qu",
            "romanche" => "roh",
            "romani" => "rmy",
            "roumain" => "ro",
            "russe" => "ru-Latn",
            "sâme du Sud" => "se",
            "samoan" => "sm",
            "sango" => "sg",
            "sanskrit" => "sa",
            "sarde" => "sc",
            "scots" => "sco",
            "serbe" => "sr",
            "shona" => "sn",
            "sicilien" => "scn",
            "sindhi" => "sd",
            "slovaque" => "sk",
            "slovène" => "sl",
            "somali" => "so",
            "sotho du Sud" => "sot",
            "soundanais" => "su",
            "suédois" => "sv",
            "swahili" => "sw",
            "tadjik" => "tg",
            "tagalog" => "tl",
            "tahitien" => "ty",
            "tamoul" => "ta",
            "tatar" => "tt",
            "tatar de Crimée" => "crh",
            "tchèque" => "cs",
            "tchétchène" => "ce",
            "tchouvache" => "cv",
            "télougou" => "te",
            "thaï" => "th",
            "tsonga" => "ts",
            "tswana" => "tn",
            "turc" => "tu",
            "turkmène" => "tk",
            "twi" => "tw",
            "ukrainien" => "uk",
            "vietnamien" => "vi",
            "vieux norrois" => "vn",
            "volapük" => "vo",
            "wallon" => "wa",
            "wolof" => "wo",
            "xhosa" => "xh",
            "yiddish" => "yi",
            "zhuang" => "za",
            "zoulou" => "zu",
        ];

    // FRANCAIS => fr-lang. Exemple : anglais => en
    private $liste_frlang
        = [
            "aa",
            "ab",
            "ace",
            "ae",
            "af",
            "an",
            "ang",
            "ar",
            "as",
            "ast",
            "ay",
            "az",
            "ba",
            "bcl",
            "be-tarask",
            "bg",
            "bh",
            "bi",
            "bm",
            "bn",
            "br",
            "ca",
            "ce",
            "ch",
            "co",
            "crh",
            "cs",
            "cv",
            "cy",
            "da",
            "de",
            "dz",
            "ee",
            "en",
            "eo",
            "es",
            "et",
            "ff",
            "fi",
            "fj",
            "fr",
            "fur",
            "fy",
            "ga",
            "gez",
            "gil",
            "gl",
            "gn",
            "grc",
            "gv",
            "ha",
            "he",
            "hif",
            "hr",
            "hsb",
            "ht",
            "hu",
            "ia",
            "id",
            "ie",
            "ig",
            "ik",
            "io",
            "is",
            "it",
            "iu",
            "ja",
            "jv",
            "kaa",
            "kab",
            "kg",
            "kk",
            "kl",
            "ko",
            "ks",
            "ku",
            "kw",
            "ky",
            "la",
            "lad",
            "lb",
            "li",
            "ln",
            "lo",
            "lt",
            "lua",
            "lv",
            "mg",
            "mk-Latn",
            "ml",
            "mn",
            "mt",
            "mus",
            "mwl",
            "nap",
            "nd",
            "nds",
            "ne",
            "new",
            "nl-be",
            "no",
            "nr",
            "oc",
            "or",
            "os",
            "pa",
            "pam",
            "pi",
            "pl",
            "ps",
            "pt",
            "qu",
            "rmy",
            "ro",
            "roa-rup",
            "roh",
            "ru-Latn",
            "sa",
            "sc",
            "scn",
            "sco",
            "sd",
            "se",
            "sg",
            "sk",
            "sl",
            "sm",
            "sn",
            "so",
            "sot",
            "sq",
            "sr",
            "su",
            "sv",
            "sw",
            "ta",
            "te",
            "tg",
            "th",
            "tk",
            "tl",
            "tn",
            "ts",
            "tt",
            "tu",
            "tw",
            "ty",
            "uk",
            "ur",
            "uz",
            "vi",
            "vn",
            "vo",
            "wa",
            "wo",
            "xh",
            "yi",
            "za",
            "zh",
            "zu",
        ];

    /**
     * LanguageEnum constructor.
     *
     * @param string $origin
     * @param string $valueLanguage
     *
     * @throws \Exception
     */
    public function __construct(
        string $origin,
        string $valueLanguage
    ) {
        if ($origin === 'fromlang') {
            $this->frlang = $valueLanguage;
            $this->origin = $origin;

            return;
        }
        throw new \Exception('No origin constant');
    }

    public function getFrLang()
    {
        return $this->frlang;
    }

    public function getFrLangText()
    {
        if (!array_key_exists($this->frlang, $this->frlang_to_french)) {
            return false;
        }

        return $this->frlang_to_french[$this->frlang];
    }

}
