# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# git stuff
git:
  submodules: false

branches:
  only:
    - master
    - develop

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.1
  allow_failures:
    - php: 7.1

# Define an environment variable
env:
  - SYMFONY_VERSION="3.3.*" DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
#  - cp app/config/parameters.yml.dist app/config/parameters.yml
#  - php bin/console doctrine:database:create --env=test
#  - php bin/console doctrine:schema:create --env=test
#  - php bin/console doctrine:fixtures:load -n --env=test

before_script:
  - composer install --dev --quiet --no-interaction
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Run script
script:
  - phpunit

# After a build, send email notification with the build results
notifications:
  email: false
