# Ce fichier de configuration est utilisé pour personnaliser le traitement de liens externes par le bot.
# Modifiez-le à votre convenance (no stress).
#
# périodique = wikification pour paramètre de {{article}}
# site = wikification pour paramètre de {{lien web}}
# template = forcer le choix du modèle : 'lien web', article, auto (pour automatique).
# desactived = le domaine sera ignoré par le bot
#
# Nuance sur les sous-domaines : entre 'test.com' et 'blabla.test.com' (les www servent à rien)
# si y'a pas d'espace ou crochets ou autre caractère louche, les guillemets sont facultatifs

lemonde.fr:
    périodique: '[[Le Monde]]'
    site: '[[Le Monde|Le Monde.fr]]'
    template: auto

leparisien.fr:
    périodique: '[[Le Parisien]]'
    template: auto

nytimes.com:
    périodique: '[[The New York Times]]'
    site: '[[nytimes.com]]'
    template: auto
movies.nytimes.com:
    site: '[[nytimes.com]]'
persee.fr:
    éditeur: '[[Persée (portail)|Persée]]'
    template: article
lequipe.fr:
    site: '[[L''Équipe]]'
    stripfromtitle: ["- L'ÉQUIPE", "L'ÉQUIPE -", "L'Équipe"]
    template: lien web
letemps.ch:
    périodique: '[[Le Temps (quotidien suisse)|Le Temps]]'
    template: auto
strategies.fr:
    site: '[[Stratégies]]'
cairn.info:
    desactived
# 403 forbidden :  Contact: DataAccess@datadome.co
ncbi.nlm.nih.gov:
    # PubMed Central
    template: article
lefigaro.fr:
    template: auto
    articleDetectType: 'NewsArticle'
    périodique: '[[Le Figaro]]'
    site: '[[Le Figaro|lefigaro.fr]]'
lavoixdunord.fr:
    périodique: '[[La Voix du Nord]]'
    template: auto
liberation.fr:
    périodique: '[[Libération (journal)|Libération]]'
    template: auto
journals.openedition.org:
    template: auto
gallica.bnf.fr:
    site: '[[Gallica]]'
courrierinternational.com:
    template: auto
    articleDetectType: 'article'
ladepeche.fr:
    template: auto
    site: '[[La Dépêche du Midi|La Dépêche]]'
    périodique: '[[La Dépêche du Midi|La Dépêche]]'

#theguardian.com:
lesechos.fr:
    template: auto
    périodiques: '[[Les Échos]]'

web.archive.org:
    # caca : URL proposée ne retient pas mot de recherche
    template: lien web
    site: '[[Internet Archive]]'
sports-reference.com:
    desactived
#ouest-france.fr:
#letempsarchives.ch:
#jstor.org:
#wrestleview.com:
la-croix.com:
    périodique: '[[La Croix]]'
    template: auto



#fin de fichier
