version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    # Install php packages and run tests
    docker:
      # https://circleci.com/developer/images/image/cimg/php
      - image: cimg/php:8.1.23-node
        environment:
          BOT_NAME: "CI-Test"
          USER_AGENT: "CI-Test"
    steps:
      - checkout
      - php/install-packages
      - run:
          name: run tests
          command: ./vendor/bin/phpunit --exclude-group=skipci --no-coverage
#  deploy:
#    docker:
#      - image: cimg/base:stable
#    steps:
#      - run:
#          name: deploy
#          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-php
    # - deploy:
    #     requires:
    #       - test-php