<?php
/*
 * This file is part of dispositif/wikibot application (@github)
 * 2019-2023 © Philippe M./Irønie  <dispositif@gmail.com>
 * For the full copyright and MIT license information, view the license file.
 */

declare(strict_types=1);

namespace App\Domain\ExternLink;

use App\Domain\Models\Wiki\AbstractWikiTemplate;
use App\Domain\Models\Wiki\ArticleTemplate;
use App\Domain\Models\Wiki\LienWebTemplate;
use App\Domain\Models\Wiki\OuvrageTemplate;
use App\Domain\Utils\WikiTextUtil;
use RuntimeException;
use Symfony\Component\Yaml\Yaml;

trait PublisherLogicTrait
{
    /**
     * todo extract Infra getcont form file + inject
     */
    protected function importConfigAndData(): void
    {
        $this->requireConfigFile(
            self::CONFIG_PRESSE,
            'manually-curated file, not regenerated by a script -- restore it from another checkout or backup'
        );
        // todo REFAC DataObject[] (WTF?)
        $this->config = Yaml::parseFile(self::CONFIG_PRESSE);
        $skipFromFile = file(
            self::SKIP_DOMAIN_FILENAME,
            FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES
        );
        $this->skip_domain = $skipFromFile ?: [];

        $this->publisherData['newspaper'] = $this->readJsonConfigFile(
            self::CONFIG_NEWSPAPER_JSON,
            'run php src/Application/CLI/wikidataFetchPresse.php to regenerate it'
        );
        $this->publisherData['scientific domain'] = $this->readJsonConfigFile(
            self::CONFIG_SCIENTIFIC_JSON,
            'run php src/Application/CLI/wikidataFetchScientific.php to regenerate it'
        );
        $this->publisherData['scientific wiki'] = $this->readJsonConfigFile(
            self::CONFIG_SCIENTIFIC_WIKI_JSON,
            'run php src/Application/CLI/wikidataFetchScientific.php to regenerate it'
        );
    }

    /**
     * These config/data files are gitignored (manually curated or Wikidata-sourced) -- a fresh
     * checkout (e.g. after a server reinstall) won't have them. Fail loudly instead of letting
     * json_decode()/Yaml::parseFile() throw an opaque error on a missing file.
     */
    private function requireConfigFile(string $path, string $howToFix): void
    {
        if (!is_file($path)) {
            throw new RuntimeException(
                sprintf('Missing config file %s -- %s.', $path, $howToFix)
            );
        }
    }

    private function readJsonConfigFile(string $path, string $howToFix): array
    {
        $this->requireConfigFile($path, $howToFix);

        return json_decode(file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
    }

    /**
     * TODO rename/move Postprocess data site/périodique
     * Replace 'site' and 'périodique' with wikidata URL of newspapers and scientific journals or config_press (YAML).
     */
    protected function replaceSitenameByConfig(array $mapData, AbstractWikiTemplate $template): array
    {
        // Wikidata replacements
        $mapData = $this->replaceWithWDataNewspaper($mapData, $template);
        $mapData = $this->replaceWithWDataSciences($mapData);

        // config_press YAML replacements
        return $this->replaceWithHumanConfig($template, $mapData);
    }

    /**
     * Replace 'site' with wikidata URL of newspapers
     */
    protected function replaceWithWDataNewspaper(array $mapData, AbstractWikiTemplate $template): array
    {
        if (!empty($this->publisherData['newspaper'][$this->registrableDomain])) {
            $frwiki = $this->publisherData['newspaper'][$this->registrableDomain]['frwiki'];
            $label = $this->publisherData['newspaper'][$this->registrableDomain]['fr'];
            if (isset($mapData['site']) || $template instanceof LienWebTemplate) {
                $mapData['site'] = WikiTextUtil::wikilink($label, $frwiki);
            }
            if (isset($mapData['périodique']) || $template instanceof ArticleTemplate) {
                $mapData['périodique'] = WikiTextUtil::wikilink($label, $frwiki);
            }
        }
        return $mapData;
    }

    /**
     * Replace 'périodique' with wikidata URL of scientific journals
     */
    protected function replaceWithWDataSciences(array $mapData): array
    {
        if (isset($mapData['périodique']) && isset($this->publisherData['scientific wiki'][$mapData['périodique']])) {
            $mapData['périodique'] = WikiTextUtil::wikilink(
                $mapData['périodique'],
                $this->publisherData['scientific wiki'][$mapData['périodique']]
            );
        }
        return $mapData;
    }

    /**
     * Replace 'site' and 'périodique' with config_press (YAML)
     */
    protected function replaceWithHumanConfig(AbstractWikiTemplate $template, array $mapData): array
    {
        $mapData = $this->replaceSiteForLienWeb($template, $mapData);
        $mapData = $this->replacePeriodique($mapData, $template);

        $mapData = $this->replaceEditor($mapData);

        $mapData = $this->stripParamValue('stripfromauthor', $mapData, 'auteur1');

        return $this->stripParamValue('stripfromtitle', $mapData, 'titre');
    }

    /**
     * config_presse.yaml entries that apply to the current URL, merged from least to most
     * specific host key : "bnf.fr", then "gallica.bnf.fr", then "www.gallica.bnf.fr".
     *
     * Lookups used to key on the registrable domain only, so every subdomain entry of the file
     * was dead config -- "gallica.bnf.fr: site: [[Gallica]]" never fired, and the (wrong)
     * Wikidata newspaper mapping for the whole of 'bnf.fr' won instead. Same for the file's
     * other subdomain keys, all flagged "todo vérifier sous-domaine" (link.springer.com,
     * journals.plos.org, hal.archives-ouvertes.fr, ncbi.nlm.nih.gov...).
     */
    protected function getDomainConfig(): array
    {
        $domainConfig = [];
        foreach ($this->getConfigDomainKeys() as $key) {
            $value = $this->config[$key] ?? null;
            if (is_array($value)) {
                $domainConfig = array_merge($domainConfig, $value);
            } elseif ('deactivated' === $value) {
                $domainConfig['deactivated'] = true; // shorthand "domain.com: deactivated"
            }
        }

        return $domainConfig;
    }

    /**
     * Host keys to look up, least specific first.
     * hostname "www.gallica.bnf.fr" => ['bnf.fr', 'gallica.bnf.fr', 'www.gallica.bnf.fr'].
     *
     * @return string[]
     */
    protected function getConfigDomainKeys(): array
    {
        return $this->buildConfigDomainKeys($this->registrableDomain ?? '', $this->hostname ?? '');
    }

    /**
     * Same key list for an arbitrary host, not necessarily the URL being processed
     * (e.g. the site archived behind a webarchive URL).
     *
     * @return string[]
     */
    protected function buildConfigDomainKeys(string $registrableDomain, string $hostname): array
    {
        $keys = ('' === $registrableDomain) ? [] : [$registrableDomain];

        if ('' === $hostname || $hostname === $registrableDomain) {
            return $keys;
        }

        $subdomains = ('' !== $registrableDomain && str_ends_with($hostname, '.' . $registrableDomain))
            ? substr($hostname, 0, -strlen('.' . $registrableDomain))
            : $hostname;

        $key = $registrableDomain;
        foreach (array_reverse(explode('.', $subdomains)) as $label) {
            $key = ('' === $key) ? $label : $label . '.' . $key;
            $keys[] = $key;
        }

        return $keys;
    }

    /**
     * Prettiest known name for an arbitrary site, e.g. "[[Gallica]]" or "[[Le Monde]]" —
     * from the same two sources |site= itself uses (config_presse.yaml first, since it's
     * manually curated, then the Wikidata newspaper mapping). Null when neither knows it,
     * the caller then falls back to the bare domain.
     *
     * Used for the site archived behind a webarchive URL, where the crawled host is the
     * archiver's ("wikiwix.com") and not the source the reader cares about.
     */
    protected function findWikifiedSiteName(string $registrableDomain, string $hostname = ''): ?string
    {
        $configSite = null;
        foreach ($this->buildConfigDomainKeys($registrableDomain, $hostname) as $key) {
            $value = $this->config[$key] ?? null;
            if (is_array($value) && !empty($value['site'])) {
                $configSite = (string)$value['site']; // most specific host key wins
            }
        }
        if ($configSite !== null) {
            return $configSite;
        }

        $newspaper = $this->publisherData['newspaper'][$registrableDomain] ?? null;
        if (!empty($newspaper['fr']) && !empty($newspaper['frwiki'])) {
            return WikiTextUtil::wikilink($newspaper['fr'], $newspaper['frwiki']);
        }

        return null;
    }

    protected function replaceSiteForLienWeb(AbstractWikiTemplate $template, array $mapData): array
    {
        $domainConfig = $this->getDomainConfig();
        if (isset($domainConfig['site']) && $template instanceof LienWebTemplate) {
            $mapData['site'] = $domainConfig['site'];
            if (empty($mapData['site'])) {
                unset($mapData['site']);
            }
        }
        return $mapData;
    }

    protected function replacePeriodique(array $mapData, AbstractWikiTemplate $template): array
    {
        $domainConfig = $this->getDomainConfig();
        if (isset($domainConfig['périodique'])
            && (!empty($mapData['périodique'])
                || $template instanceof OuvrageTemplate)
        ) {
            $mapData['périodique'] = $domainConfig['périodique'];
            if (empty($mapData['périodique'])) {
                unset($mapData['périodique']);
            }
        }
        return $mapData;
    }

    /**
     * Replace 'éditeur' on {article} todo move
     */
    protected function replaceEditor(array $mapData): array
    {
        $domainConfig = $this->getDomainConfig();
        if (isset($domainConfig['éditeur'])
            && !empty($mapData['éditeur'])) {
            $mapData['éditeur'] = $domainConfig['éditeur'];
            if (empty($mapData['éditeur'])) {
                unset($mapData['éditeur']);
            }
        }
        return $mapData;
    }

    /**
     * Use config_press stripFromAuthor (string array) and stripFromTitle, to remove text from author and title.
     */
    protected function stripParamValue(string $configParam, array $mapData, string $templateParam): array
    {
        $domainConfig = $this->getDomainConfig();
        if (!empty($domainConfig[$configParam])
            && !empty($mapData[$templateParam])) {
            $stripText = $domainConfig[$configParam]; // string|array
            $mapData[$templateParam] = trim(str_ireplace($stripText, '', (string) $mapData[$templateParam]));
            if (empty($mapData[$templateParam])) {
                unset($mapData[$templateParam]);
            }
        }
        return $mapData;
    }

    protected function isScientificDomain(): bool
    {
        if (isset($this->publisherData['scientific domain'][$this->registrableDomain])) {
            return true;
        }
        return strpos('.revues.org', (string) $this->registrableDomain) > 0;
    }
}