#!/usr/bin/env php
<?php

namespace App;

use App\Application\WikiPageContentCommand;
use Symfony\Component\Console\Application;

include __DIR__.'/Application/bootstrap.php';

$console = new Application();
$console->add(new WikiPageContentCommand());

// Bug on command with arguments related to symfony/.../input/ArgvInput.php
// Symfony\Component\Console\Exception\InvalidArgumentException: The "1"
// argument does not exist. in wikibot/vendor/symfony/console/Input/InputDefinition.php on line 135
// => Downgrading symfony/console (v4.3.4 => v4.2.0)

try{
    $console->run();
}catch (\Throwable $e){
    die($e);
}

